# Generated by Django 5.2 on 2025-04-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publisted_date',
            new_name='published_date',
        ),
    ]
